/* Cartes utilisees par le jeu de memoire.
   Les visuels sont ceux du set Blurness 3, stockes dans assets/cards/.
   Fichier statique : aucune requete reseau, le jeu tourne hors ligne. */

const CARTES = [
  { id: "essence-rose", nom: "Essence Rose", image: "assets/cards/001-essence-rose.webp" },
  { id: "essence-orange", nom: "Essence Orange", image: "assets/cards/002-essence-orange.webp" },
  { id: "essence-jade", nom: "Essence Jade", image: "assets/cards/003-essence-jade.webp" },
  { id: "essence-violette", nom: "Essence Violette", image: "assets/cards/004-essence-violette.webp" },
  { id: "essence-jaune", nom: "Essence Jaune", image: "assets/cards/005-essence-jaune.webp" },
  { id: "essence-mauve", nom: "Essence Mauve", image: "assets/cards/006-essence-mauve.webp" },
  { id: "essence-verte", nom: "Essence Verte", image: "assets/cards/007-essence-verte.webp" },
  { id: "essence-bleue", nom: "Essence Bleue", image: "assets/cards/008-essence-bleue.webp" },
  { id: "essence-azur", nom: "Essence Azur", image: "assets/cards/009-essence-azur.webp" },
  { id: "vandale", nom: "Vandale", image: "assets/cards/011-vandale.webp" },
  { id: "squeezie-le-toxique", nom: "Squeezie Le Toxique", image: "assets/cards/012-squeezie-le-toxique.webp" },
  { id: "pas-compris", nom: "Pas compris", image: "assets/cards/013-pas-compris.webp" },
  { id: "tout-commence-ici", nom: "Tout Commence Ici", image: "assets/cards/017-tout-commence-ici.webp" },
  { id: "buy-bundle-m8", nom: "BUY BUNDLE M8 !!", image: "assets/cards/018-buy-bundle-m8.webp" },
  { id: "oce-pce", nom: "OCE/PCE", image: "assets/cards/019-oce-pce.webp" },
  { id: "namifique", nom: "Namifique", image: "assets/cards/022-namifique.webp" },
  { id: "marteen-supreme", nom: "Marteen Supreme", image: "assets/cards/023-marteen-supreme.webp" },
  { id: "gentle-mates-minny", nom: "Gentle Mates Minny", image: "assets/cards/025-gentle-mates-minny.webp" },
  { id: "pause-technique", nom: "Pause Technique", image: "assets/cards/026-pause-technique.webp" },
  { id: "remontada", nom: "Remontada", image: "assets/cards/027-remontada.webp" },
  { id: "championnes-d-europe", nom: "CHAMPIONNES D'EUROPE", image: "assets/cards/028-championnes-d-europe.webp" },
  { id: "pollo", nom: "Pollo", image: "assets/cards/029-pollo.webp" },
  { id: "worlds-lyon", nom: "Worlds Lyon", image: "assets/cards/030-worlds-lyon.webp" },
  { id: "moi-je-suis-coach", nom: "Moi je suis coach", image: "assets/cards/031-moi-je-suis-coach.webp" },
  { id: "invitation", nom: "Invitation", image: "assets/cards/032-invitation.webp" },
  { id: "visa-refuse", nom: "Visa Refusé", image: "assets/cards/033-visa-refuse.webp" },
  { id: "vanyabubu", nom: "Vanyabubu", image: "assets/cards/034-vanyabubu.webp" },
  { id: "pitchounes", nom: "Pitchounes", image: "assets/cards/035-pitchounes.webp" },
  { id: "l-oeil-de-nikof", nom: "L'oeil de Nikof", image: "assets/cards/037-l-oeil-de-nikof.webp" },
  { id: "zero-soucis", nom: "Zéro Soucis", image: "assets/cards/039-zero-soucis.webp" },
  { id: "reverse-squeeze", nom: "Reverse Squeeze", image: "assets/cards/042-reverse-squeeze.webp" },
  { id: "blblblbl", nom: "BLBLBLBL", image: "assets/cards/043-blblblbl.webp" },
  { id: "zzzzzzz", nom: "Zzzzzzz", image: "assets/cards/045-zzzzzzz.webp" },
  { id: "champions-du-major", nom: "CHAMPIONS DU MAJOR", image: "assets/cards/047-champions-du-major.webp" },
  { id: "champions-du-major-2", nom: "CHAMPIONS DU MAJOR", image: "assets/cards/048-champions-du-major.webp" },
  { id: "le-roi-des-rois", nom: "Le Roi des rois", image: "assets/cards/049-le-roi-des-rois.webp" },
  { id: "la-planete", nom: "La Planète", image: "assets/cards/051-la-planete.webp" },
  { id: "target-missed", nom: "Target Missed", image: "assets/cards/055-target-missed.webp" },
  { id: "maillot-maudit", nom: "Maillot Maudit", image: "assets/cards/056-maillot-maudit.webp" },
  { id: "siborg", nom: "Siborg", image: "assets/cards/057-siborg.webp" },
  { id: "ghosty-in-finals", nom: "Ghosty in Finals", image: "assets/cards/058-ghosty-in-finals.webp" },
  { id: "baby-driver", nom: "Baby Driver", image: "assets/cards/059-baby-driver.webp" },
  { id: "gotaga-pose", nom: "Gotaga Pose", image: "assets/cards/060-gotaga-pose.webp" },
  { id: "champions-du-major-3", nom: "CHAMPIONS DU MAJOR", image: "assets/cards/061-champions-du-major.webp" },
  { id: "just-passion", nom: "Just Passion", image: "assets/cards/063-just-passion.webp" },
  { id: "calma", nom: "Calma", image: "assets/cards/064-calma.webp" },
  { id: "bwarks", nom: "Bwarks", image: "assets/cards/065-bwarks.webp" },
  { id: "jus-de-bagarre", nom: "Jus de bagarre", image: "assets/cards/066-jus-de-bagarre.webp" },
  { id: "1-chance", nom: "1% chance", image: "assets/cards/068-1-chance.webp" },
  { id: "99-faith", nom: "99% faith", image: "assets/cards/069-99-faith.webp" },
  { id: "l-arme-nucleaire", nom: "L'Arme Nucléaire", image: "assets/cards/070-l-arme-nucleaire.webp" },
  { id: "versus-fighting", nom: "Versus Fighting", image: "assets/cards/072-versus-fighting.webp" },
  { id: "leakof", nom: "Leakof", image: "assets/cards/073-leakof.webp" },
  { id: "l-heritier", nom: "L'Héritier", image: "assets/cards/073-l-heritier.webp" },
  { id: "grand-respect", nom: "Grand Respect", image: "assets/cards/075-grand-respect.webp" },
  { id: "petrodollars", nom: "Pétrodollars", image: "assets/cards/076-petrodollars.webp" },
  { id: "brawks-deter", nom: "Brawks Déter", image: "assets/cards/078-brawks-deter.webp" },
  { id: "le-chevalier-rose", nom: "Le Chevalier Rose", image: "assets/cards/079-le-chevalier-rose.webp" },
  { id: "instalock", nom: "Instalock", image: "assets/cards/080-instalock.webp" },
  { id: "mon-cogneur", nom: "Mon Cogneur", image: "assets/cards/082-mon-cogneur.webp" },
  { id: "barakataga", nom: "Barakataga", image: "assets/cards/083-barakataga.webp" },
  { id: "mercato", nom: "Mercato", image: "assets/cards/084-mercato.webp" },
  { id: "la-chevaliere", nom: "La Chevalière", image: "assets/cards/085-la-chevaliere.webp" },
  { id: "cooked", nom: "Cooked", image: "assets/cards/086-cooked.webp" },
  { id: "gros-bonnet", nom: "Gros Bonnet", image: "assets/cards/088-gros-bonnet.webp" },
  { id: "m4", nom: "M4", image: "assets/cards/089-m4.webp" },
  { id: "la-luxueuse-i", nom: "La Luxueuse I", image: "assets/cards/090-la-luxueuse-i.webp" },
  { id: "la-luxueuse-ii", nom: "La Luxueuse II", image: "assets/cards/091-la-luxueuse-ii.webp" },
  { id: "clim", nom: "Clim", image: "assets/cards/093-clim.webp" },
  { id: "alerte-leak", nom: "Alerte Leak", image: "assets/cards/094-alerte-leak.webp" },
  { id: "one-more", nom: "ONE MORE", image: "assets/cards/095-one-more.webp" },
  { id: "tunnel", nom: "Tunnel", image: "assets/cards/096-tunnel.webp" },
  { id: "tweet-la-defaite", nom: "Tweet la Défaite", image: "assets/cards/097-tweet-la-defaite.webp" },
  { id: "doig-dance", nom: "Doig'Dance", image: "assets/cards/098-doig-dance.webp" },
  { id: "meta-coeurs", nom: "Méta Coeurs", image: "assets/cards/099-meta-coeurs.webp" },
  { id: "meta-f-ck", nom: "Méta F*ck", image: "assets/cards/100-meta-f-ck.webp" },
  { id: "le-loup-du-game", nom: "Le Loup du Game", image: "assets/cards/101-le-loup-du-game.webp" },
  { id: "slay", nom: "SLAY", image: "assets/cards/102-slay.webp" },
  { id: "monster", nom: "Monster", image: "assets/cards/103-monster.webp" },
  { id: "joueur-de-l-ombre", nom: "Joueur de l'ombre", image: "assets/cards/103-joueur-de-l-ombre.webp" },
  { id: "lofi-girl", nom: "Lofi Girl", image: "assets/cards/105-lofi-girl.webp" },
  { id: "m16", nom: "M16", image: "assets/cards/106-m16.webp" },
  { id: "trahison", nom: "Trahison++", image: "assets/cards/107-trahison.webp" },
  { id: "keynote", nom: "Keynote", image: "assets/cards/109-keynote.webp" },
  { id: "hatewatch", nom: "Hatewatch", image: "assets/cards/110-hatewatch.webp" },
  { id: "leakof-2", nom: "Leakof", image: "assets/cards/111-leakof.webp" },
  { id: "la-gaming-house", nom: "La Gaming House", image: "assets/cards/112-la-gaming-house.webp" },
  { id: "m8-resilience", nom: "M8 Résilience", image: "assets/cards/112-m8-resilience.webp" },
  { id: "sbg", nom: "SBG", image: "assets/cards/114-sbg.webp" },
  { id: "champions-du-monde", nom: "CHAMPIONS DU MONDE !", image: "assets/cards/115-champions-du-monde.webp" },
  { id: "la-releve", nom: "La Relève", image: "assets/cards/117-la-releve.webp" },
  { id: "gotaga-dance", nom: "Gotaga Dance", image: "assets/cards/118-gotaga-dance.webp" },
  { id: "gotaga-circus", nom: "Gotaga Circus", image: "assets/cards/119-gotaga-circus.webp" },
  { id: "le-marionnettiste", nom: "Le Marionnettiste", image: "assets/cards/121-le-marionnettiste.webp" },
  { id: "la-luxueuse-iii", nom: "La Luxueuse III", image: "assets/cards/123-la-luxueuse-iii.webp" },
  { id: "brawks-trop-deter", nom: "Brawks Trop Déter", image: "assets/cards/125-brawks-trop-deter.webp" },
  { id: "paris-gentle-mates", nom: "Paris Gentle Mates", image: "assets/cards/127-paris-gentle-mates.webp" },
];

const DOS_DE_CARTE = "assets/card-back.webp";
